service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1

  custom:
    fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

  plugins:
    - serverless-iam-roles-per-function

   
            

  resources:
    Resources:
      FileBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:custom.fileUploadBucketName}
          AccessControl: PublicRead